# Generated by Django 3.2.3 on 2021-05-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(default='測試測試', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='pic_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/8/84/Dufu.jpg', max_length=250),
            preserve_default=False,
        ),
    ]
